# <div align="center"> ![Logo](https://www.ups.edu.ec/ups_portal-theme/images/ups/home/logo-ups-home.png)
# <div align="center">  Minimax y Alpha-Beta prunning
## Materia:
### <div align="center"> Inteligencia Artificial
## Docentes:
### <div align="center"> Ing. Diego Quisi
## • Historia
El famoso matemático Alan Turing, nación en Londres en el año de 1912 y murió en el año de 1954 a la edad de 42 años en Wilmslow en Reino Unido, durante años se ha especulado si su muerte fue un suicido o un accidente. En sus inicios sus estudios los realizo en la india. Para el año de 1937 uno de sus artículos que permitió su conocimiento como un matemático británico brillante fue la publicación de la obra La Máquina de Turing, se trataba de una máquina calculadora con capacidad, que para su funcionamiento base de instrucciones lógicas, lo que futuro se conoció como base de algoritmo. Al concluir los años 40, Alan Turing fue el que desarrollo el primer programa de ajedrez, que era un programa de ordenador, para ello también desarrollo un artículo de nombre Digital Computer Applied to Game*, que posteriormente sería la base para el desarrollo de juegos de ajedrez, para su desarrollo Alan Turing para seleccionar el mejor movimiento seleccionaba aquel que da una mejor evaluación.
    
## • Inicio de juegos de inteligencias artificial.     
Cuando ya era posible la programación (1950). Claude Shannon conocido como el padre de la teoría de la información, junto con Alan Turing fueron los pioneros en desarrollo de los primeros programas de Inteligencia Artificial.

## • Minimax
El algoritmo minimax es el algoritmo más conocido para juegos de 2 adversarios, movimientos alternos. En teoría de juegos, minimax es un método de decisión para minimizar la perdida máxima esperada en juegos con adversario, es un cálculo que se realiza de forma recursiva. En simples palabras el algoritmo de minimax consiste en la elección del mejor movimiento para el computador, suponiendo que el contrincante escogerá uno que lo pueda perjudicar, para escoger la mejor opción este algoritmo realiza un árbol de búsqueda con todos los posibles movimientos, luego recorre todo el árbol de soluciones del juego a partir de un estado dado, es decir, según las casillas que ya han sido rellenadas. Por tanto, minimax se ejecutará cada vez que le toque mover a la IA.
    - CARACTERISTICAS -Solucionar problemas complejos con reglas simples.
        * Existe un solo ganador.
        * Tiempo de exploración agotado.
        * Utiliza procedimientos recursivos.
# <div align="center"> ![Img1](https://i.stack.imgur.com/DC33H.png)
## •  Pasos que sigue minimax
    
    - El algoritmo primero generar un árbol de soluciones completo a partir de un nodo dado.
    - Para cada nodo final, buscamos la función de utilidad de estos. Es decir por ejemplo usaremos un 0 para las partidas que terminen en empate, un 1 para las que gane la IA y un -1 para las que gane el jugador humano.
    - Y lo que hará el algoritmo Minimax cuando vaya regresando hacia atrás, será comunicarle a la llamada recursiva superior cuál es el mejor nodo hoja alcanzado hasta el momento. Cada llamada recursiva tiene que saber a quién le toca jugar, para analizar si el movimiento realizado pertenece a la IA o al otro jugador, ya que cuando sea el turno de la IA nos interesa MAXIMIZAR el resultado, y cuando sea el turno del rival MINIMIZAR su resultado. Al final el algoritmo nos devolverá la jugada que debe realizar la máquina para maximizar sus posibilidades y bloquear las posibilidades del rival.


## • Alpha-beta pruning
Se basa en una mejor del algoritmo anteriormente descrito, su mejora radica en que es posible poder calcular el estado objetivo sin la necesidad de recorrer todos los nodos del árbol, al igual que el anterior algoritmo hace el uso de la búsqueda en profundidad.
La poda alfa beta es una técnica de búsqueda que reduce el número de nodos evaluados en un árbol de juego por el algoritmo Minimax. Se trata de una técnica muy utilizada en programas de juegos entre adversarios como el ajedrez, el tres en raya o el Go.

## • Explicar mediante un ejemplo práctico el funcionamiento del algoritmo.
### Tres en Raya   
Es una configuración inicial del juego, es decir, un estado en el que se encuentre el juego. Para nuestro ejemplo sería:
# <div align="center"> ![Img2](https://lh4.googleusercontent.com/C5Vfv7R7ZiQfWzp1zWLf6fPviQhqJVO2p-0mdk7XI6HErm9VRp50-KVCT30veSsr8lTK0A2SrTp6QNoYRXN-AJBdl4U0ChE-GWGNEjypYY8cHX-7SGGgyWoLUvvPzuRNZGSMj-3x)   
Para cada nodo final, buscamos la función de utilidad de estos. En nuestro ejemplo usaremos un 0 para las partidas que terminen en empate, un 1 para las que gane la IA y un -1 para las que gane el jugador humano.
# <div align="center"> ![Img2](https://lh3.googleusercontent.com/EhNl7Cozbwprh0Ift0baBsN0380e033cefxI35suEQFZKcPNjeP4ZPlaCLjvZtEHnB548Xi4RbYzOc7E_cEb5GiIRnLUOd-mgH7hFCXJG2M7qJ2HKfo3JBKfGpk_pFksXZMR2iEf)   
Y lo que hará el algoritmo Minimax cuando vaya regresando hacia atrás, será comunicarle a la llamada recursiva superior cuál es el mejor nodo hoja alcanzado hasta el momento. Cada llamada recursiva tiene que saber a quién le toca jugar, para analizar si el movimiento realizado pertenece a la IA o al otro jugador, ya que cuando sea el turno de la IA nos interesa MAXIMIZAR el resultado, y cuando sea el turno del rival MINIMIZAR su resultado.
# <div align="center"> ![Img3](https://lh4.googleusercontent.com/OUMzX0zeRYXmFt-qie9oEtiIbapRJVUh_NQz83OqE3WeukFX82ngkjEcJNv8AiID5mMHPvyXI1AmGs_LygXO8K9yVhJQKRuUGNF6dtGYtdAL30ivl1G3XgHrspAVeX8VkK2lD3mp)   
Y lo que hará el algoritmo Minimax cuando vaya regresando hacia atrás, será comunicarle a la llamada recursiva superior cuál es el mejor nodo hoja alcanzado hasta el momento. Cada llamada recursiva tiene que saber a quién le toca jugar, para analizar si el movimiento realizado pertenece a la IA o al otro jugador, ya que cuando sea el turno de la IA nos interesa MAXIMIZAR el resultado, y cuando sea el turno del rival MINIMIZAR su resultado.   
Al final el algoritmo nos devolverá la jugada que debe realizar la máquina para maximizar sus posibilidades y bloquear las posibilidades del rival.
# <div align="center">Revisar al menos 4 papers científicos de aplicaciones prácticas de este algoritmo y su variante.
    *  https://www.sciencedirect.com/science/article/abs/pii/S0004370283800101
    *  https://www.sciencedirect.com/science/article/abs/pii/S0004370283800101
    *  https://www.researchgate.net/publication/280558518_Utilizacao_de_Tecnicas_e_Heuristicas_em_Algoritmos_para_Jogos
    *  https://www.researchgate.net/publication/327057359_Algoritmos_para_Igualdades_Minimax_em_Grafos
# <div align="center">  Ejemplo Practico
### Tres en Raya    

In [2]:
from easyAI import TwoPlayersGame, Human_Player, AI_Player, Negamax
import numpy as np
class TresEnRaya(TwoPlayersGame):
    
    def __init__(self,nplayers):
        self.tablero = np.zeros((3,3),dtype = int)
        self.nplayer = 1
        self.mapa = {}
        cont = 1
        for i in range(len(self.tablero)):
            for j in range(len(self.tablero)):
                self.mapa[cont]=(i,j)
                cont+=1
                
        #print(self.mapa)
        self.players = nplayers
        
    def possible_moves(self):
        moves = []
        cont = 1
        for i in range(len(self.tablero)):
            for j in range(len(self.tablero)):
                if self.tablero[i][j] == 0:
                    moves.append(cont)
                cont+=1
                
        #print(moves)
        return moves
    
    def make_move(self,casillero):
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = self.nplayer
        
    def unmake_move(self,casillero):
        pos = self.mapa[casillero]
        self.tablero[pos[0]][pos[1]] = 0
        
    def lose(self):
        for i in range(len(self.tablero)):
            if np.all(self.tablero[i,:]==self.nopponent,axis = 0) or np.all(self.tablero[:,i]==self.nopponent,axis = 0):
                return True
        if self.tablero[0][0]==self.nopponent and self.tablero[1][1]==self.nopponent and self.tablero[2][2]==self.nopponent:
            return True
        if self.tablero[2][0]==self.nopponent and self.tablero[1][1]==self.nopponent and self.tablero[0][2]==self.nopponent:
            return True
        return False
    
    def show(self):
        print(self.tablero)
        
    def scoring(self):
        return -100 if self.lose() else 0
        
    def is_over(self):
        return (self.possible_moves() == [] or self.lose())
            
    
if __name__=="__main__":
    ai_algo = Negamax(6)
    tresenraya = TresEnRaya([Human_Player(),AI_Player(ai_algo)])
    tresenraya.play()

[[0 0 0]
 [0 0 0]
 [0 0 0]]

Player 1 what do you play ? 5

Move #1: player 1 plays 5 :
[[0 0 0]
 [0 1 0]
 [0 0 0]]

Move #2: player 2 plays 1 :
[[2 0 0]
 [0 1 0]
 [0 0 0]]

Player 1 what do you play ? 2

Move #3: player 1 plays 2 :
[[2 1 0]
 [0 1 0]
 [0 0 0]]

Move #4: player 2 plays 8 :
[[2 1 0]
 [0 1 0]
 [0 2 0]]

Player 1 what do you play ? 4

Move #5: player 1 plays 4 :
[[2 1 0]
 [1 1 0]
 [0 2 0]]

Move #6: player 2 plays 6 :
[[2 1 0]
 [1 1 2]
 [0 2 0]]

Player 1 what do you play ? 4

Player 1 what do you play ? 5

Player 1 what do you play ? 6

Player 1 what do you play ? 7

Move #7: player 1 plays 7 :
[[2 1 0]
 [1 1 2]
 [1 2 0]]

Move #8: player 2 plays 3 :
[[2 1 2]
 [1 1 2]
 [1 2 0]]

Player 1 what do you play ? 9

Move #9: player 1 plays 9 :
[[2 1 2]
 [1 1 2]
 [1 2 1]]


# <div align="center">  Desarrollar un mini-juego (tema libre) empleando: easyAI | Universe | GYM

In [13]:
class Awele(TwoPlayersGame):

    def __init__(self, players):
        for i, player in enumerate(players):
            player.score = 0
            player.isstarved = False
            player.camp = i
        self.players = players
        self.board = [1, 4, 1, 4, 4, 4,
                      4, 1, 1, 4, 4, 4]

        self.nplayer = 1  # player 1 starts.

    def make_move(self, move):
        if move == "None":
            self.player.isstarved = True
            s = 6 * self.opponent.camp
            self.player.score += sum(self.board[s:s + 6])
            return

        move = 'abcdefghijkl'.index(move)

        pos = move
        for i in range(self.board[move]):  # DEAL
            pos = (pos + 1) % 12
            if pos == move:
                pos = (pos + 1) % 12
            self.board[pos] += 1

        self.board[move] = 0

        while ((pos / 6) == self.opponent.camp
               and (self.board[pos] in [2, 3])):  # TAKE
            self.player.score += self.board[pos]
            self.board[pos] = 0
            pos = (pos - 1) % 12

    def possible_moves(self):

        if self.nplayer == 1:
            if max(self.board[:6]) == 0: return ['None']
            moves = [i for i in range(6) if (self.board[i] >= 6 - i)]
            if moves == []:
                moves = [i for i in range(6) if self.board[i] != 0]
        else:
            if max(self.board[6:]) == 0: return ['None']
            moves = [i for i in range(6, 12) if (self.board[i] >= 12 - i)]
            if moves == []:
                moves = [i for i in range(6, 12) if self.board[i] != 0]

        return ['abcdefghijkl'[u] for u in moves]

    def show(self):

        print("Puntaje: %d / %d" % tuple(p.score for p in self.players))
        print('  '.join('lkjihg'))
        print(' '.join(["%02d" % i for i in self.board[-1:-7:-1]]))
        print(' '.join(["%02d" % i for i in self.board[:6]]))
        print('  '.join('abcdef'))

    def lose(self):
        return self.opponent.score > 24

    def is_over(self):
        return (self.lose() or
                sum(self.board) < 7 or
                self.opponent.isstarved)


In [14]:
scoring = lambda game: game.player.score - game.opponent.score
ai = Negamax(6, scoring)
game = Awele([AI_Player(ai), AI_Player(ai)])
game.play()

if game.player.score > game.opponent.score:
    print("Jugador %d gana" % game.nplayer)
elif game.player.score < game.opponent.score:
    print("Jugador %d gana" % game.nopponent)
else:
    print("Empate")

Puntaje: 0 / 0
l  k  j  i  h  g
04 04 04 01 01 04
01 04 01 04 04 04
a  b  c  d  e  f

Move #1: player 1 plays d :
Puntaje: 0 / 0
l  k  j  i  h  g
04 04 04 01 02 05
01 04 01 00 05 05
a  b  c  d  e  f

Move #2: player 2 plays j :
Puntaje: 0 / 0
l  k  j  i  h  g
05 05 00 01 02 05
02 05 01 00 05 05
a  b  c  d  e  f

Move #3: player 1 plays b :
Puntaje: 0 / 0
l  k  j  i  h  g
05 05 00 01 02 06
02 00 02 01 06 06
a  b  c  d  e  f

Move #4: player 2 plays g :
Puntaje: 0 / 3
l  k  j  i  h  g
06 06 01 02 03 00
00 00 02 01 06 06
a  b  c  d  e  f

Move #5: player 1 plays f :
Puntaje: 0 / 3
l  k  j  i  h  g
07 07 02 03 04 01
00 00 02 01 06 00
a  b  c  d  e  f

Move #6: player 2 plays k :
Puntaje: 0 / 3
l  k  j  i  h  g
08 00 02 03 04 01
01 01 03 02 07 01
a  b  c  d  e  f

Move #7: player 1 plays f :
Puntaje: 2 / 3
l  k  j  i  h  g
08 00 02 03 04 00
01 01 03 02 07 00
a  b  c  d  e  f

Move #8: player 2 plays l :
Puntaje: 2 / 3
l  k  j  i  h  g
00 00 02 03 05 01
02 02 04 03 08 01
a  b  c  d  e  f

Mo